services:
  backend:
    build: ./backend
    container_name: jeopardy-backend
    ports:
      - "3001:3001"
    environment:
      - SQLITE_LOCAL_DSN=${SQLITE_LOCAL_DSN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - ./backend/jeopardy.db:/app/jeopardy.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: jeopardy-frontend
    ports:
      - "3002:80"
    depends_on:
      - backend
    restart: unless-stopped 